brand: "Our Family"
navigation:
  - label: "About Us"
    href: "#about"
  - label: "Home & Life"
    href: "#home-life"
  - label: "Gallery"
    href: "#gallery"
  - label: "Contact"
    href: "#contact"
cta:
  label: "Get in touch"
  href: "#contact"
hero:
  eyebrow: "Welcome to Our Family"
  headline: "We're Alex & Jordan, and we can't wait to share our story with you."
  description: "We are a loving couple who have been together for 8 wonderful years. Our home is filled with laughter, kindness, and a deep sense of adventure."
  cta_label: "Learn more about us"
  cta_href: "#about"
  scroll_hint: "Scroll to explore"
about:
  title: "Meet Us"
  intro: "We believe that family is built on unconditional love, and we're excited to grow ours through adoption."
  people:
    - name: "Alex"
      title: "Teacher & Creative Soul"
      bio: "Alex is a kindergarten teacher who finds joy in watching children discover and grow. They love biking around the neighborhood, hiking trails near our home, and hosting Sunday dinners."
      quote: "I'm passionate about learning, making, and trying new things—especially when we get to do it together."
      image: "partner1.jpg"
    - name: "Jordan"
      title: "Outdoor Enthusiast & Nature Lover"
      bio: "Jordan is a community organizer who loves building connections. Their favorite place is the local park, where we spend weekends walking our dog and meeting neighbors."
      quote: "I'm looking forward to sharing life with a child and creating memories in the everyday moments."
      image: "partner2.jpg"
home_life:
  title: "Our Home & Life"
  description: "We live in a cozy, light-filled house on a quiet street, surrounded by parks, libraries, and a welcoming community."
  highlights:
    - title: "A cozy space to grow"
      text: "Our favorite spot is the sunlit living room, where we read, craft, and dream together."
      image: "home-exterior.jpg"
    - title: "Community at our doorstep"
      text: "Neighbors gather for block parties, and the nearby park is perfect for bike rides and picnics."
      image: "neighborhood-park.jpg"
    - title: "Weekends full of life"
      text: "From farmer's markets to cooking with friends, we love filling our weekends with warmth and laughter."
      image: "friends-gathering.jpg"
gallery:
  title: "Little glimpses of our life"
  images:
    - caption: "Weekend hike on our favorite trail"
      image: "hiking-adventure.jpg"
    - caption: "Cooking together on Sunday"
      image: "cooking-together.jpg"
    - caption: "Quiet evenings in the neighborhood park"
      image: "couple-together.jpg"
contact:
  title: "Let's connect"
  message: "If you'd like to know more about us or our story, we'd love to hear from you."
  button_label: "Get in touch"
  button_href: "mailto:hello@ourfamilystory.com"
