brand: "Our Family"
navigation:
  - label: "About Us"
    href: "#about"
  - label: "Home & Life"
    href: "#home-life"
  - label: "Fun Facts"
    href: "#quick-answers"
  - label: "Our World"
    href: "#map"
  - label: "Our Village"
    href: "#our-village"
  - label: "Our Journey"
    href: "#timeline"
  - label: "Daily Life"
    href: "#daily-life"
  - label: "Gallery"
    href: "#gallery"
  - label: "Contact"
    href: "#contact"
cta:
  label: "Get in touch"
  href: "#contact"
hero:
  eyebrow: "Welcome to Our Family"
  headline: "We're Brett & Sebastian, and we can't wait to share our story with you."
  description: "We are a loving couple who have been together for 8 wonderful years. Our home is filled with laughter, kindness, and a deep sense of adventure."
  cta_label: "Learn more about us"
  cta_href: "#about"
  scroll_hint: "Scroll to explore"
  video_url: "https://www.youtube.com/embed/0syaBf0x3mU?si=tr6-ZfzTjJtm7-t2"
  video_title: "A glimpse into our family's story"
  video_caption: "Take a quick look at the warmth, laughter, and adventures that fill our days."
about:
  title: "Meet Us"
  intro: "We believe that family is built on unconditional love, and we're excited to grow ours through adoption."
  people:
    - name: "Brett"
      title: "Operations Manager & Board Game Lover"
      bio: "Brett is an operations manager who finds joy in watching children discover and grow. They love biking around the neighborhood, hiking trails near our home, and hosting Sunday dinners."
      quote: "I'm passionate about learning, making, and trying new things—especially when we get to do it together."
      image: "brett.jpg"
    - name: "Sebastian"
      title: "Data Scientist & Outdoor Enthusiast"
      bio: "Sebastian is a data scientist who loves building connections. Their favorite place is the local park, where we spend weekends walking our dog and meeting neighbors."
      quote: "I'm looking forward to sharing life with a child and creating memories in the everyday moments."
      image: "sebastian.jpg"
quick_answers:
  title: "Quick questions, honest answers"
  subtitle: "A few of our favorites right now"
  items:
    - question: "Favorite superhero"
      answers:
        - person: "Brett"
          response: "Miles Morales—his courage and creativity remind me to stay curious and kind."
        - person: "Sebastian"
          response: "Ms. Marvel. I love her optimism, humor, and commitment to community."
    - question: "Go-to comfort meal"
      answers:
        - person: "Brett"
          response: "Veggie lasagna layered with ricotta and roasted veggies—cozy every time."
        - person: "Sebastian"
          response: "Tomato basil soup with crusty bread, especially on rainy evenings."
    - question: "Favorite children's book"
      answers:
        - person: "Brett"
          response: "'The Snowy Day'—I love its gentle magic and beautiful illustrations."
        - person: "Sebastian"
          response: "'Last Stop on Market Street' because it celebrates gratitude and community."
    - question: "Weekend ritual"
      answers:
        - person: "Brett"
          response: "Farmer's market stroll, then we cook something new together."
        - person: "Sebastian"
          response: "Bike to the park, throw a frisbee, and grab coffee on the way home."
    - question: "Favorite color"
      answers:
        - person: "Brett"
          response: "Warm terracotta—it's earthy, cozy, and shows up all over our home."
        - person: "Sebastian"
          response: "Deep forest green because it reminds me of hiking under tall trees."
our_village:
  title: "Our Village"
  subtitle: "The people who cheer us on"
  intro: "We are surrounded by a loving circle of family and friends who are ready to welcome a child with open arms and warm hearts."
  entries:
    - title: "Grandparents"
      subtitle: "Endless love and gentle wisdom"
      body: "Both sets of grandparents live nearby and bring patience, laughter, and the sweetest homemade treats. They are eager for park walks, library trips, and cozy storytimes with their future grandchild."
      image: "grandparents.jpg"
    - title: "Friends & Family"
      subtitle: "Weekly traditions and constant support"
      body: "Our closest friends and siblings gather for Sunday dinners, game nights, and backyard bonfires. They show up for every milestone and can't wait to share their joy, stories, and traditions with a little one."
      image: "friends-together.jpg"
home_life:
  title: "Our Home & Neighborhood"
  subtitle: "Where love lives and memories are made"
  description: "Our cozy four-bedroom home sits on a tree-lined street in a welcoming neighborhood. We have a big backyard perfect for playing, a sunny kitchen where we love to cook together, and a dedicated playroom ready for a child's imagination. The neighborhood is full of friends, and there's always someone to wave hello to on our evening walks."
  spotlights:
    - title: "Our Home"
      image: "home-exterior.jpg"
      description: "A warm, inviting space filled with light and laughter"
    - title: "Our Neighborhood"
      image: "neighborhood.png"
      description: "Tree-lined streets, playgrounds, and friendly neighbors"
  features:
    - title: "Cozy Family Home"
      description: "4 bedrooms, a big backyard, and a bright living room ready for playtime and family gatherings."
      icon: "home"
    - title: "Great Parks Nearby"
      description: "Parks and playgrounds just minutes away, perfect for weekend adventures."
      icon: "park"
    - title: "Excellent Schools"
      description: "Highly-rated schools, just 5 minutes away with wonderful teachers and plenty to explore."
      icon: "school"
    - title: "Friendly Community"
      description: "A close-knit neighborhood with block parties, holiday celebrations, and warm, caring neighbors."
      icon: "community"
map:
  heading: "Where our story is rooted"
  intro: "From coastlines to mountain trails, these are the places that have shaped our love story, family traditions, and dreams for the future."
  markers:
    - title: "Hometown"
      subtitle: "Brett's roots"
      description: "The small coastal city where Brett grew up biking to the pier, visiting the farmer's market, and learning to cook with their grandmother."
      image: "home-exterior.jpg"
      x_percent: 32
      y_percent: 42
    - title: "Where we met"
      subtitle: "A neighborhood concert"
      description: "We first crossed paths at a summer block party filled with live music, string lights, and the laughter of new friends."
      image: "friends-gathering.jpg"
      x_percent: 41
      y_percent: 52
    - title: "Weekend escape"
      subtitle: "Our favorite trail"
      description: "A mountain hike just a short drive away where we recharge with fresh air, big views, and quiet walks together."
      image: "hiking-adventure.jpg"
      x_percent: 83
      y_percent: 30
timeline:
  title: "Our Journey to Adoption"
  description: "Moments that brought us from our first hello to the heartfelt decision to grow our family through adoption."
  events:
    - title: "We met at a neighborhood concert"
      timestamp: "Summer 2015"
      description: "A mutual friend introduced us beneath twinkling string lights at a block party. We spent the whole evening trading stories and laughing until closing time."
    - title: "Building our first home together"
      timestamp: "Autumn 2017"
      description: "After finding our cozy house, we painted the walls, filled the rooms with plants, and hosted a housewarming dinner that truly made it feel like ours."
    - title: "Celebrating our engagement"
      timestamp: "Spring 2019"
      description: "Sebastian proposed during a sunrise hike on our favorite trail. We toasted with thermos coffee and promised to keep adventuring side by side."
    - title: "Choosing adoption with full hearts"
      timestamp: "This year"
      description: "After years of conversations, volunteering with kids, and dreaming about the future, we knew adoption was the path meant for us."
daily_glimpse:
  title: "A Glimpse Into Our Days"
  description: "From slow mornings to weekend adventures, we love the simple rhythms that make our life feel warm, connected, and full of wonder."
  activities:
    - title: "Outdoor adventures"
      description: "We head to the nearby trails whenever we can—walking our dog, spotting wildlife, and soaking up fresh mountain air together."
      image: "outdoor-hiking.jpg"
    - title: "Cooking & creating"
      description: "Our kitchen is the heart of our home. We cook side-by-side, try new recipes, and invite friends over for cozy dinners."
      image: "cooking-together.jpg"
    - title: "Time with friends"
      description: "Game nights, backyard bonfires, and block parties keep us close to the people we love and the community we cherish."
      image: "friends-hiking.jpg"
gallery:
  title: "Little glimpses of our life"
  images:
    - caption: "Weekend hike on our favorite trail"
      image: "hiking-adventure.jpg"
    - caption: "Cooking together on Sunday"
      image: "cooking-together.jpg"
    - caption: "Quiet evenings in the neighborhood park"
      image: "couple-together.jpg"
letter_to_birth_mother:
  title: "A letter to the birth mother"
  subtitle: "From our hearts to yours"
  greeting: "Dear birth mother,"  
  intro: "We honor your strength, courage, and the love you hold for your child."
  body:
    - "Thank you for considering us as adoptive parents. We approach this journey with deep respect for you and the hopes and dreams you carry for your baby."
    - "Our home is filled with kindness, laughter, and a community ready to support your child. We promise to create a space where they always feel safe, cherished, and celebrated for exactly who they are."
    - "We will speak about you with love and gratitude, sharing your story as part of our family's story. You will always hold an honored place in our hearts and in the life of your child."
  closing: "With gratitude and care,"
  signature: "Brett & Sebastian"
contact:
  title: "Let's connect"
  message: "If you'd like to know more about us or our story, we'd love to hear from you."
  button_label: "Get in touch"
  button_href: "mailto:hello@ourfamilystory.com"
